### ISSUE TITLE
freqs column order

### ISSUE THREAD

**Issue by robmaz** [kathrinannaotte/haplovalidate#5]
The examples

  ### define which columns of the sync file contain the base population
  base.pops <- c(rep(TRUE, length(repl)),rep(FALSE,length(repl)*(length(gens)-1)))

as well as the initial code (haplovalidate, line 4)

  base.pops <- c(rep(TRUE, length(repl)), rep(FALSE, length(repl) * 
    (length(gens) - 1)))

suggest that the expected order of allele frequency columns in the "cands" argument is
first by replicate, then by generation, e.g.,

   base_r1   base_r2 ... base_r5   F10_r1 ... F10_r5   F20_r1   ...   F60_r5

However, the AF matrix is then appears to be initialized with a different order in mind (haplovalidate, line 48)

   ts.all[[d]] <- try(initialize_SNP_time_series(chr = cands[chr == 
        d, chr], pos = cands[chr == d, pos], base.freq = cands[chr == 
        d, basePops], lib.freqs = cands[chr == d, afcolis, 
        with = F], **pop.ident = c(rep(repl, each = length(gens))), 
        pop.generation = rep(gens, length(repl))**, use.libs = compare, 
        min.minor.freq = min.minor.freq, max.minor.freq = max.minor.freq, 
        winsize = winsize, win.scale = "bp", min.lib.frac = min.lib.frac, 
        minfreqchange = minfreqchange, minrepl = minrepl), 
        silent = T)

and used like this when fed to reconstruct_hb (haplovalidate, line 66).

On the face of it, this looks like this is in effect randomly remixing the frequency trajectories,
and thus like a serious bug?

**Comment by kathrinannaotte** [comment]
Hi @robmaz ,

thanks for spotting this issue! 

This is not a serious bug, as the order of replicates/generations is not relevant for the downstream functionality of haplovalidate, i.e. changing this order should not affect the identified reconstructed haplotype blocks. 

However, as it is inconsistent and highly confusing, I will generate a new version and handle this issue in a more intuitive way.

Cheers
Kathrin

**Comment by kathrinannaotte** [comment]
I updated haplovalidate and created version 0.1.5, which allows the user to explicitly specify the order of generations and replicates.
