### ISSUE TITLE
file 'cands.all' is full of NA values

### ISSUE THREAD

**Issue by ouc-zzh** [kathrinannaotte/haplovalidate#6]
the example: I have 5 generations (0,2,7,10,14). 10 samples per generation. My sample .snyc file is in order (F0_sample1,F0_sample2,...,F14_sample9,F14_sample10).
 
repl <- 1:10
gens <- c(0,2,7,10,14)
base.pops <- c(rep(TRUE, length(repl)),rep(FALSE,length(repl)*(length(gens)-1)))
compare <- rep(TRUE,length(repl)*length(gens))
pop.ident <- rep(repl,length(gens))
pop.generation  <- rep(gens, each=length(repl))
cands.all <- sync_to_frequencies(syncfile,base.pops=base.pops,header=FALSE,mincov=15)

I didn't include ‘polaRise’, because I do not understand the line "polaRise = list(c(1,26),c(2,27), C (3,28),c(4,29),c(5,30))" in README.md. Why use 'c(1,26)'? How does this relate to the sample order in the .snyc file? 

My file "cands.all" are all NA values at last, which makes me very confused. May I ask what the problem is?

Thank you!

**Comment by kathrinannaotte** [comment]
Hi, 

the sync_to_frequency function is part of the haploReconstruct package. From the help you can get more infos for all the parameters to set, polaRise in particular polarizes your SNPs for the rising allele between the two columns specified for a particular replicate, e.g. in your case for it would be 1 and 41 for replicate 1 (Generation 0 and 14), 2 and 42 for replicate 2 etc . You need to set this parameter to get proper correlations. 

According to the NAs my best guess is that your SNPs are filtered out by the function according to the mincov parameter, is your coverage below 15 ?

I hope this helps?
Kathrin

**Comment by ouc-zzh** [comment]
> Hi,
> 
> the sync_to_frequency function is part of the haploReconstruct package. From the help you can get more infos for all the parameters to set, polaRise in particular polarizes your SNPs for the rising allele between the two columns specified for a particular replicate, e.g. in your case for it would be 1 and 41 for replicate 1 (Generation 0 and 14), 2 and 42 for replicate 2 etc . You need to set this parameter to get proper correlations.
> 
> According to the NAs my best guess is that your SNPs are filtered out by the function according to the mincov parameter, is your coverage below 15 ?
> 
> I hope this helps? Kathrin

Hi,

My .sync file was generated by 'popoolation2' software, using re-duplicated .bam files. 

Now  I use this following command:  
cands.all <- sync_to_frequencies("C:/Users/OUC-ZZH/Desktop/JF.target.sync",base.pops=base.pops,header=F,polaRise = polaRise,mincov=10)
But, it is still full of NA.

**Comment by kathrinannaotte** [comment]
Hello,

could you please send a minimal example of your sync file with SNPs/lines that end up NA in the cands.all object? 

Thanks!
Kathrin

**Comment by ouc-zzh** [comment]
> Hello,
> 
> could you please send a minimal example of your sync file with SNPs/lines that end up NA in the cands.all object?
> 
> Thanks! Kathrin

[Desktop.zip](https://github.com/kathrinannaotte/haplovalidate/files/11068611/Desktop.zip)
Hi:



OK,Attached is my snyc file and the R script I ran. 

My command to generate the snyc file is:

java -ea -Xmx7g -jar mpileup2sync.jar --input JF.target.mpileup --output JF.target.sync --fastq-type sanger --min-qual 20 --threads 8


Thanks!

**Comment by kathrinannaotte** [comment]
Hi,

your sync file has very low coverage in a lot of SNPs, so its is not possible to calculate reliable allele frequency changes. The sync_to_frequency function excludes all SNPs in which one or more of the time points do not meet the minimal coverage (e.g. 10), this is why they end up NA in your cands.all object. 

Cheers
Kathrin
